#!/bin/bash

set -euo pipefail

readonly URL=$1

query_endpoint() {
    local url=$1
    curl -i -H "Content-Type: application/json" $url
    printf "\n"
}

main() {
    printf "Invoking '${URL}' endpoints...\n"
    query_endpoint "${URL}/v1/request"
    query_endpoint "${URL}/v1/resource"
    query_endpoint "${URL}/v1/load/5s"
}

main

