#!/bin/bash

set -euo pipefail

readonly URL=$1
readonly VERSION=$2

main() {
    local current=$(curl -H "Content-Type: application/json" \
        "${URL}/v1/request/info" | jq -r ".request.version")

    if [ "$current" != "$VERSION" ]; then
        printf "invalid version, expected: ${VERSION}, got: ${current}\n"
        exit 1
    fi
    printf "version: ${current}\n"
}

main

