version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
- directory: /
  package-ecosystem: "terraform"
  schedule:
    timezone: "daily"