#!/bin/bash

# capture project ID from gcloud config
BUCKET="restme-dev-flow-terraform-state"
PID=$(gcloud config get-value project)

# create bucket if not exists
gsutil ls -b "gs://${PID}-${BUCKET}" || \
    gsutil mb -c STANDARD -l US-WEST1 -b on "gs://${PID}-${BUCKET}"

# init terraform with the state bucket and flow prefix 
terraform init -backend-config="bucket=${PID}-${BUCKET}"
