#!/bin/bash

gcloud beta compute security-policies rules create 2000 \
    --security-policy=restme-policy \
    --expression="request.headers['host'] == 'restme.cloudylab.dev'" \
    --action=throttle \
    --rate-limit-threshold-count=10 \
    --rate-limit-threshold-interval-sec=60 \
    --conform-action=allow \
    --exceed-action=deny-429 \
    --enforce-on-key=IP

# test throttle
# for i in {1..100}; do curl -i https://restme.cloudylab.dev/v1/request/info; done