#!/bin/bash

export REPO="mchmarny/restme"

gcloud iam service-accounts create restme-sa --project $PROJECT_ID

gcloud projects add-iam-policy-binding $PROJECT_ID \
    --member=user:"restme-sa@${PROJECT_ID}.iam.gserviceaccount.com" \
    --role=roles/resourcemanager.projectCreator

gcloud services enable iamcredentials.googleapis.com --project $PROJECT_ID}

gcloud iam workload-identity-pools create restme-pool \
  --project $PROJECT_ID \
  --location global \
  --display-name 'restme pool'

gcloud iam workload-identity-pools describe restme-pool \
  --project $PROJECT_ID \
  --location global \
  --format 'value(name)'

export WORKLOAD_IDENTITY_POOL_ID="$(gcloud iam workload-identity-pools describe restme-pool \
  --project ${PROJECT_ID} \
  --location global \
  --format 'value(name)')"

gcloud iam workload-identity-pools providers create-oidc restme-provider \
  --project $PROJECT_ID \
  --location global \
  --workload-identity-pool restme-pool \
  --display-name "restme provider" \
  --attribute-mapping "google.subject=assertion.sub,attribute.actor=assertion.actor,attribute.repository=assertion.repository" \
  --issuer-uri "https://token.actions.githubusercontent.com"

gcloud iam service-accounts add-iam-policy-binding "restme-sa@${PROJECT_ID}.iam.gserviceaccount.com" \
  --project $PROJECT_ID \
  --role "roles/iam.workloadIdentityUser" \
  --member "principalSet://iam.googleapis.com/${WORKLOAD_IDENTITY_POOL_ID}/attribute.repository/${REPO}"

gcloud iam workload-identity-pools providers describe restme-provider \
  --project $PROJECT_ID \
  --location "global" \
  --workload-identity-pool restme-pool \
  --format='value(name)'



