name: PRB Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:

  test:
    runs-on: ubuntu-latest
    steps:

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Tidy Modules
      run: |
        make tidy

    - name: Config Lint
      id: golangci_config
      uses: andstor/file-existence-action@v1
      with:
        files: .golangci.yaml

    - name: Lint Code
      if: steps.golangci_config.outputs.files_exists == 'true'
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.40
        args: --timeout 3m

    - name: Lint Code 
      if: steps.golangci_config.outputs.files_exists == 'true'
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.38
        args: --timeout 3m

    - name: Test Code
      run: |
        make test
        
        