name: Build Test

on: 
  repository_dispatch:
    types: [build]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Version
      run: |
        echo "RELEASE_VERSION=$(make version)" >> $GITHUB_ENV

    - name: Image
      id: image
      uses: docker/build-push-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: ./test/Dockerfile
        tags: ${GITHUB_REPOSITORY}-tester:${{ env.RELEASE_VERSION }}

    - name: Digest
      run: echo ${{ steps.image.outputs.digest }}