name: Build Test

on: 
  repository_dispatch:
    types: [build]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Version
      run: |
        echo "RELEASE_VERSION=$(make version)" >> $GITHUB_ENV

    - name: Image
      uses: docker/build-push-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: ./test/Dockerfile
        tags: ${{ env.RELEASE_VERSION }},${{ github.event.client_payload.ts }},latest