name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:

  test:
    runs-on: ubuntu-latest
    steps:

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Cache Go Modules
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Init CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: go
    
    - name: CodeQL Build
      uses: github/codeql-action/autobuild@v1
    
    - name: CodeQL Analyze
      uses: github/codeql-action/analyze@v1

    - name: Tidy Modules
      run: |
        make tidy

    - name: Config Lint
      id: golangci_config
      uses: andstor/file-existence-action@v1
      with:
        files: .golangci.yaml

    - name: Lint Code
      if: steps.golangci_config.outputs.files_exists == 'true'
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest
        args: --timeout 3m

    - name: Test Code
      run: |
        make test
        
        